### ISSUE TITLE
Dependency notes

### ISSUE THREAD

**Issue by stefandesu** [gbv/login-server#83]
Tracking dependency issues here:

- [ ] `inquirer` v9 requires the app to be an ES module (https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%409.0.0) (#110)
- [x] `mongodb` v6 and `express-rate-limit` v7 require Node.js 16.20.1 (#105)
- [x] `mongodb` v6 can only be updated when [this PR](https://github.com/jdesboeufs/connect-mongo/pull/473) for `connect-mongo` is merged
- [ ] `meow` v10 requires the app to be an ES module (and v12 requires Node.js 16) (#110, #105)

**Comment by stefandesu** [comment]
Also we need to fix the issue with GitHub dependencies that causes GitHub Actions to fail. See also: https://github.com/actions/setup-node/issues/214

**Comment by stefandesu** [comment]
Updated in https://github.com/gbv/login-server/commit/c30ade4fd83f06e96e45e76fb9315f4c58729472 (forgot to tag).
